import type { ContentType } from "./platform";

// ─── Credit deduction API ─────────────────────────────────────────────────────

// Creator Systems calls this when a fan triggers paid content generation.
// Idempotent on transactionId — safe to retry.
export interface CreditDeductionRequest {
  transactionId: string; // idempotency key; UUID v4 generated by Creator Systems
  fanId: string;
  creatorId: string;
  jobId: string;
  contentType: ContentType;
  creditsToDeduct: number; // positive integer; validated server-side against credit table
  requestedAt: string; // ISO 8601
}

export type CreditDeductionErrorCode =
  | "insufficient_credits"
  | "fan_not_found"
  | "creator_not_found"
  | "duplicate_transaction" // returned only on exact-duplicate non-idempotent retry
  | "job_already_charged";

export interface CreditDeductionResponse {
  transactionId: string;
  fanId: string;
  creditsDeducted: number;
  creditsRemaining: number;
  success: boolean;
  errorCode: CreditDeductionErrorCode | null;
  processedAt: string; // ISO 8601
}

// ─── Payout webhook interface ─────────────────────────────────────────────────

export type PayoutWebhookEventType =
  | "payout.scheduled"
  | "payout.processing"
  | "payout.completed"
  | "payout.failed"
  | "payout.reversed";

export type PayoutCurrency = "USD" | "JPY" | "TWD";
export type PayoutProvider = "stripe" | "line_pay";

export interface PayoutWebhookEvent {
  eventId: string; // idempotency key
  eventType: PayoutWebhookEventType;
  payoutId: string;
  creatorId: string;
  amountCents: number; // amount in smallest currency unit (cents / yen / TWD)
  currency: PayoutCurrency;
  payoutProvider: PayoutProvider;
  timestamp: string; // ISO 8601
  metadata: Record<string, string>;
}

// ─── Payout summary ───────────────────────────────────────────────────────────

export interface PayoutSummary {
  payoutId: string;
  creatorId: string;
  periodStart: string; // ISO 8601
  periodEnd: string; // ISO 8601
  totalCreditsEarned: number;
  grossAmountCents: number; // before platform fee
  platformFeeCents: number; // 30% default; exact rate in creator_config
  netAmountCents: number; // disbursed amount
  currency: PayoutCurrency;
  payoutProvider: PayoutProvider;
  status: "pending" | "processing" | "paid" | "failed";
  scheduledAt: string; // ISO 8601
  paidAt: string | null; // ISO 8601; null until paid
}

// ─── Credit balance ───────────────────────────────────────────────────────────

export interface FanCreditBalance {
  fanId: string;
  credits: number; // current spendable balance
  reservedCredits: number; // held for in-flight jobs; not yet deducted
  lastUpdatedAt: string; // ISO 8601
}
